#!/bin/sh
### BEGIN INIT INFO
# Provides: pigpiod
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: 
# Description: Start pigpiod at boot
### END INIT INFO

DIR=/home/pi/BigDigitalClock/src
DAEMON=/usr/local/bin/pigpiod
DAEMON_NAME=pigpiod

DAEMON_OPTS=""

DAEMON_USER=root

PIDFILE="/var/run/pigpio.pid"

. /lib/lsb/init-functions

do_start() {
    log_daemon_msg "Starting $DAEMON_NAME"
    start-stop-daemon --chdir "$DIR" --start --background --pidfile $PIDFILE --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}

do_stop() {
    log_daemon_msg "Stopping $DAEMON_NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in
 start|stop)
   do_${1}
   ;;

 restart|reload|force-reload)
   do_stop
   do_start
   ;;

 status)
   status_of_proc -p "$PIDFILE" "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
   ;;

 *)
   echo "Usage: /etc/init.d/PigpioService {start|stop|restart|status}"
   exit 1
   ;;
esac

exit 0
